name: Build
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up our JDK environment
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 19
      - name: Build apk
        run: ./gradlew assembleRelease
      - name: Sign APK
        id: sign_apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNINGKEYBASE64 }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTOREPASSWORD }}
          keyPassword: ${{ secrets.KEYPASSWORD }}
      - name: Upload app
        uses: actions/upload-artifact@v3
        with:
          name: app-release-signed
          path: ${{steps.sign_apk.outputs.signedReleaseFile}}
      - name: Upload backend
        uses: actions/upload-artifact@v3
        with:
          name: backend
          path: backend/build/libs/backend-all.jar
