name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Set up our JDK environment
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 19
      - name: Run Kotlin Linter
        run: ./gradlew ktlintStagingDebugCheck
      - name: Run Unit Tests
        run: ./gradlew testStagingDebugUnitTest
    runs-on: ubuntu-latest
