name: Build
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up our JDK environment
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 19
      - name: Build apk
        run: ./gradlew assemble
      - name: Upload app
        uses: actions/upload-artifact@v3
        with:
          name: app-release-unsigned.apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk
      - name: Upload backend
        uses: actions/upload-artifact@v3
        with:
          name: backend-all.jar
          path: backend/build/libs/backend-all.jar
